#!/bin/bash
g++ lab8_1.cpp -o lab8_1 -lpthread
g++ lab8_2.cpp -o lab8_2 -lpthread
gnome-terminal --title="Writer (lab8_1, SVID)" -- ./lab8_1
gnome-terminal --title="Reader (lab8_2, SVID)" -- ./lab8_2
